<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="38412" started-at="2017-03-29T04:03:49Z" finished-at="2017-03-29T04:04:27Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="38412" started-at="2017-03-29T04:03:49Z" finished-at="2017-03-29T04:04:27Z">
      <class name="com.test.southwest.Newtest">
        <test-method status="PASS" signature="prerequisites()[pri:0, instance:com.test.southwest.Newtest@6beff444]" name="prerequisites" is-config="true" duration-ms="35871" started-at="2017-03-29T09:33:49Z" finished-at="2017-03-29T09:34:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- prerequisites -->
        <test-method status="FAIL" signature="a()[pri:0, instance:com.test.southwest.Newtest@6beff444]" name="a" duration-ms="260" started-at="2017-03-29T09:34:24Z" finished-at="2017-03-29T09:34:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Element not found in object file]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Element not found in object file
	at org.testng.Assert.fail(Assert.java:94)
	at com.test.southwest.Driver.getPageElement(Driver.java:95)
	at com.test.southwest.Newtest.a(Newtest.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- a -->
        <test-method status="PASS" signature="close()[pri:0, instance:com.test.southwest.Newtest@6beff444]" name="close" is-config="true" duration-ms="2233" started-at="2017-03-29T09:34:25Z" finished-at="2017-03-29T09:34:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- com.test.southwest.Newtest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
